[pytest]
# Example of a pytest.ini configuration
addopts = -v --maxfail=3 --tb=short
testpaths = tests
# Add custom markers for organizing tests
markers =
    basic: mark a test as a basic test.
    discovery: mark a test as a discovery test.
	logging: mark a test as a logging test.
	exception: mark a test as an exception test.
# Logging options
log_cli = true
log_cli_level = DEBUG
log_cli_format = %(asctime)s %(levelname)s %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
log_file = tests/pytest.log
log_file_level = DEBUG
